Retrello hook form
Popshow2011/retrello pull request #5
Opened 2023-12-12 21:11 UTC by Popshow2011

2023-12-19 09:14 UTC, kglazkov requested changes

2023-12-19 09:14 UTC, kglazkov commented on src/pages/Table/NewTodo.tsx
> +      axios.post('https://jsonplaceholder.typicode.com/todos', {
Валидацию нужно прикрутит на title. В данном случае проверка на пустоту и проверку на то, что новое значение не совпадает с предыдущим.

2024-01-23 06:06 UTC, Popshow2011 commented on src/pages/Table/NewTodo.tsx
> +      axios.post('https://jsonplaceholder.typicode.com/todos', {
Фикс залит

2024-01-23 12:14 UTC, kglazkov approved these changes
Так то ок, но на будущее ознакомься с formState и что оттуда можно получить...

2024-01-23 12:14 UTC, kglazkov commented on src/pages/Table/EditTodo.tsx
> +    const prevValue = (await trigger('title')) || '';
для этого есть  useFormState и у него параметры isDirty и dirtyFields... нет смысла городить велосипед

2024-01-23 13:28 UTC, merged